version: "3"

networks:

  private_network:
    ipam:
      driver: default
      config:
        - subnet: 10.2.0.0/24


services:

  unbound:
    container_name: unbound
    image: mvance/unbound:latest
    restart: unless-stopped
    volumes:
      - ./unbound:/opt/unbound/etc/unbound/
    hostname: unbound
    networks:
      private_network:
        ipv4_address: 10.2.0.200
    cap_add:
      - NET_ADMIN

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    depends_on: [unbound]
    environment:
      TZ: Europe/Berlin
      ServerIP: 10.2.0.100 # Internal IP of Pi-Hole
      DNS1: 10.2.0.200 # Unbound
      DNS2: 10.2.0.200 # Unbound again (otherwise it will pick Google DNS)
    volumes:
      - ./pihole/pihole:/etc/pihole/
      - ./pihole/dnsmasq:/etc/dnsmasq.d/
    hostname: pihole
    networks:
      private_network:
        ipv4_address: 10.2.0.100
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
    dns:
      - 127.0.0.1
      - 10.2.0.200 # Unbound
